sounds = {}
sounds.Battle = love.audio.newSource("sounds/Battle.mp3", "stream")
sounds.Battle:setVolume(0.22)
sounds.Castle = love.audio.newSource("sounds/Castle.mp3", "stream")
sounds.Castle:setVolume(0.11)
sounds.Walk = love.audio.newSource("sounds/Walk.mp3", "stream")
sounds.Walk:setVolume(0.11)
sounds.Victory = love.audio.newSource("sounds/Victory.mp3", "stream")
sounds.Victory:setVolume(0.11)
sounds.Orb = love.audio.newSource("sounds/Orb.mp3", "static")
sounds.Orb:setVolume(1.6)
sounds.Slash = love.audio.newSource("sounds/Slash.mp3", "static")
sounds.Death = love.audio.newSource("sounds/Death.mp3", "static")
sounds.Death:setVolume(1.5)
sounds.Stab = love.audio.newSource("sounds/Stab.mp3", "static")
sounds.Sword = love.audio.newSource("sounds/Sword.mp3", "static")
sounds.Walk:setLooping(true)